# Generated by Django 5.0.3 on 2024-03-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessPlannerAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseequipment',
            name='is_optional',
            field=models.BooleanField(default=False),
        ),
    ]
