# Generated by Django 5.0.3 on 2024-03-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessPlannerAPI', '0002_exerciseequipment_is_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='exercises',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='musclegroups',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
