# Generated by Django 5.0.3 on 2024-03-12 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessPlannerAPI', '0004_workoutplan_workoutplandays_workoutplanexercises'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weekday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='workoutplanexercises',
            name='workout_plan',
        ),
        migrations.AddField(
            model_name='workoutplanexercises',
            name='workout_plan_day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FitnessPlannerAPI.workoutplan'),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='weekdays',
            field=models.ManyToManyField(related_name='workout_plans_days', to='FitnessPlannerAPI.weekday'),
        ),
        migrations.DeleteModel(
            name='WorkoutPlanDays',
        ),
    ]
