# Generated by Django 5.0.3 on 2024-03-12 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessPlannerAPI', '0005_weekday_remove_workoutplanexercises_workout_plan_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workoutplan',
            old_name='weekdays',
            new_name='workout_day',
        ),
        migrations.RenameField(
            model_name='workoutplanexercises',
            old_name='workout_plan_day',
            new_name='workout_plan',
        ),
        migrations.AddField(
            model_name='workoutplanexercises',
            name='weekday',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FitnessPlannerAPI.weekday'),
        ),
    ]
