# Generated by Django 5.0.3 on 2024-03-12 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessPlannerAPI', '0006_rename_weekdays_workoutplan_workout_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutplan',
            name='workout_day',
        ),
        migrations.CreateModel(
            name='WorkoutPlanWeekdays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FitnessPlannerAPI.workoutplan')),
                ('weekday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FitnessPlannerAPI.weekday')),
            ],
            options={
                'unique_together': {('plan', 'weekday')},
            },
        ),
        migrations.CreateModel(
            name='WorkoutDayExercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.IntegerField(help_text='Number of sets')),
                ('repetitions', models.IntegerField(blank=True, help_text='Number of repetitions', null=True)),
                ('duration', models.IntegerField(blank=True, help_text='Duration in seconds', null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FitnessPlannerAPI.exercises')),
                ('plan_weekday', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FitnessPlannerAPI.workoutplanweekdays')),
            ],
        ),
        migrations.DeleteModel(
            name='WorkoutPlanExercises',
        ),
    ]
