# Generated by Django 5.0.3 on 2024-03-12 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessPlannerAPI', '0007_remove_workoutplan_workout_day_workoutplanweekdays_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutdayexercises',
            name='plan_weekday',
        ),
        migrations.DeleteModel(
            name='WorkoutPlanWeekdays',
        ),
    ]
