# Generated by Django 5.0.3 on 2024-03-12 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessPlannerAPI', '0008_remove_workoutdayexercises_plan_weekday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutdayexercises',
            name='day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FitnessPlannerAPI.weekday'),
        ),
        migrations.AddField(
            model_name='workoutdayexercises',
            name='workout_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FitnessPlannerAPI.workoutplan'),
        ),
    ]
