# Generated by Django 5.0.3 on 2024-03-12 23:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessPlannerAPI', '0009_workoutdayexercises_day_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workoutdayexercises',
            unique_together={('day', 'workout_plan', 'exercise')},
        ),
        migrations.AlterUniqueTogether(
            name='workoutplan',
            unique_together={('user', 'title')},
        ),
    ]
