# Generated by Django 5.0.3 on 2024-03-13 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessPlannerAPI', '0010_alter_workoutdayexercises_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(help_text='Running Distance', max_length=100)),
                ('target_value', models.IntegerField(help_text='Target value for the metric')),
                ('target_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'metric', 'target_date')},
            },
        ),
        migrations.CreateModel(
            name='ProgressLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('current_value', models.IntegerField(help_text='Current value for the metric')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FitnessPlannerAPI.goal')),
            ],
            options={
                'unique_together': {('goal', 'date')},
            },
        ),
    ]
