# Generated by Django 5.0.3 on 2024-03-13 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessPlannerAPI', '0011_goal_progresslog'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='progresslog',
            unique_together={('goal', 'current_value')},
        ),
    ]
